CONTIKI_PROJECT = hello-world blink-hello timer-test sensors-demo  ds18b20connet dht11connet bh1750fviconnet  project project_time project_demo

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
