CONTIKI_PROJECT = hello-world blink-hello timer-test sensors-demo mpu6050connet ds18b20connet dht11connet

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
